server:
  port: 9003
  servlet:
    context-path: /mac/api
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/,http://localhost:8889/eureka/
  instance:
    lease-renewal-interval-in-seconds: 1 #\u6BCF\u95F4\u96941s\uFF0C\u5411\u670D\u52A1\u7AEF\u53D1\u9001\u4E00\u6B21\u5FC3\u8DF3\uFF0C\u8BC1\u660E\u81EA\u5DF1\u4F9D\u7136\u201D\u5B58\u6D3B
    lease-expiration-duration-in-seconds: 2 #\u544A\u8BC9\u670D\u52A1\u7AEF\uFF0C\u5982\u679C\u62111s\u4E4B\u5185\u6CA1\u6709\u7ED9\u4F60\u53D1\u5FC3\u8DF3\uFF0C\u5C31\u4EE3\u8868\u6211\u201C\u6B7B\u201D\u4E86\uFF0C\u5C06\u6211\u8E22\u51FA\u6389\u3002
spring:
  application:
    name: hello-service
